[versions]
agp = "8.13.1"
androidxActivityKtx = "1.12.0"
animatedWebp = "3.6.0"
appcompatVersion = "1.7.1"
cardview = "1.0.0"
constraintlayout = "2.2.1"
espressoCoreVersion = "3.7.0"
fresco = "3.6.0"
googleMaterial = "1.13.0"
gson = "2.13.2"
htmlDsl = "1.0.0"
kotlin = "2.2.21"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
kotlinStdlibJdk7 = "2.1.20"
kotlinxCoroutinesAndroid = "1.10.2"
material = "1.13.0"
materialVersion = "1.13.0"
multidex = "2.0.1"
navigationFragmentKtx = "2.9.6"
photodraweeview = "2.1.0"
playServicesAds = "24.8.0"
recyclerview = "1.4.0"
roomRuntime = "2.8.4"
runner = "1.7.0"

[libraries]
androidx-appcompat-v161 = { module = "androidx.appcompat:appcompat", version.ref = "appcompatVersion" }
androidx-cardview = { module = "androidx.cardview:cardview", version.ref = "cardview" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-espresso-core-v351 = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCoreVersion" }
androidx-multidex = { module = "androidx.multidex:multidex", version.ref = "multidex" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationFragmentKtx" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntime" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
androidx-runner = { module = "androidx.test:runner", version.ref = "runner" }
animated-webp = { module = "com.facebook.fresco:animated-webp", version.ref = "animatedWebp" }
fresco = { module = "com.facebook.fresco:fresco", version.ref = "fresco" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
html-dsl = { module = "com.jaredrummler:html-dsl", version.ref = "htmlDsl" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
kotlin-stdlib-jdk7 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk7", version.ref = "kotlinStdlibJdk7" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
material-v1110alpha01 = { module = "com.google.android.material:material", version.ref = "googleMaterial" }
material-v190 = { module = "com.google.android.material:material", version.ref = "materialVersion" }
photodraweeview = { module = "me.relex:photodraweeview", version.ref = "photodraweeview" }
play-services-ads = { module = "com.google.android.gms:play-services-ads", version.ref = "playServicesAds" }
webpsupport = { module = "com.facebook.fresco:webpsupport", version.ref = "animatedWebp" }
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "androidxActivityKtx" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

